name: opensf
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytorch::pytorch=2.0.0
  - pytorch::torchvision
  - pytorch::pytorch-cuda=11.8
  - conda-forge::lightning=2.0.1
  - nvidia/label/cuda-11.8.0::cuda
  - nvidia/label/cuda-11.8.0::cuda-toolkit
  - mkl==2024.0.0
  - tensorboard
  - numba
  - numpy
  - pandas
  - pip
  - scipy
  - tqdm
  - h5py
  - wandb
  - omegaconf
  - hydra-core
  - fire
  - tabulate
  - scikit-learn
  - hdbscan
  - setuptools==69.5.1
  - gxx_linux-64==11.4.0
  - pathtools
  - rerun-sdk
  - pip:
    - assets/cuda/chamfer3D
    - assets/cuda/mmcv
    - open3d==0.18.0
    - av2==0.3.1
    - spconv-cu118==2.3.6
    - numpy==1.26.4
    # Qingwen's public pkg:
    - dztimer
    - dufomap==1.1.0
    - linefit==1.1.0

# Reason about the version fixed:
# setuptools==68.5.1: https://github.com/aws-neuron/aws-neuron-sdk/issues/893
# mkl==2024.0.0: https://github.com/pytorch/pytorch/issues/123097#issue-2218541307
# av2==0.2.1: in case other version deleted some functions.
# lightning==2.0.1: https://stackoverflow.com/questions/76647518/how-to-fix-error-cannot-import-name-modelmetaclass-from-pydantic-main
# open3d==0.18.0: because 0.17.0 have bug on set the view json file
# dufomap==1.1.0: in case later updating may not compatible with the code.
